all: myls mysearch mystat mytail

myls: myls-Jun.c
	gcc -o myls myls-Jun.c

mysearch: mysearch-Jun.c
	gcc -o mysearch mysearch-Jun.c

mystat: mystat-Jun.c
	gcc -o mystat mystat-Jun.c

mytail: mytail-Jun.c
	gcc -o mytail mytail-Jun.c